kind: Service
apiVersion: v1
metadata:
  namespace: devops
  name: backend-service
spec:
  ports:
    - port: 8181
      targetPort: 8181
      protocol: TCP
  selector:
    app: backend
  type: LoadBalancer